### PR TITLE
Add details popup and store an id in the query string to share a specific result

### LINKED ISSUE #47: Possible to have a detail page for apps?
If I'm looking to link someone to the app, it'd be helpful to have a route that takes in the app id.

For example, if I search `7zip` like this:

https://scoop.sh/#/apps?s=0&d=1&o=true&q=7zip

I get several results:

image

But if I want to share the url with someone, they have to decipher which version I meant.

Is it possible to direct link to a specific app?  There are several links in each card to the main website, the licence, the commit, and the release version, but they all take me off the scoop website.  But I couldn't find a way to click to load a single app, similar to how npm handles this:

**Search**: https://www.npmjs.com/search?q=7zip  
**Detail**: https://www.npmjs.com/package/7zip

### PR DESCRIPTION
**Pull request by gpailler**
Fix #47 

- Details popup is displayed when result name is clicked
- Result id is stored in the query string
- Details popup is displayed when a result id is found in the query string (useful when an URL is shared)

Cia7Xk4RlG

### CODE REVIEW

**Comment by gpailler** [comment]
@rashil2000 Once this PR is approved, the change will be automatically deployed to the staging URL https://scoop.sh/scoopinstaller-dev.github.io to allow us to run some extra tests on the feature.

**Review by rashil2000 — APPROVED** [review]

**Comment by rashil2000** [comment]
Approved! Is there a workflow that waits for approvals here?

**Comment by gpailler** [comment]
I merged the PR and the changes are visible on https://scoop.sh/scoopinstaller-dev.github.io
If everything looks good, I can approve the deployment to prod

**Comment by rashil2000** [comment]
Looks great!

**Pull request merged**
