### PR TITLE
Add OpenSearch functionality

### PR DESCRIPTION
**Pull request by oneminch**
Add OpenSearch functionality so that Scoop.sh can be added as a search engine to browsers.

scoop-screenshot

### CODE REVIEW

**Comment by rashil2000** [comment]
Hmm, this looks interesting, but why is package-lock.json changed?

**Comment by oneminch** [comment]
I ran `npm update` as per the README. It's the result of that command.

**Comment by rashil2000** [comment]
Those changes are not required here, so you should remove them

**Comment by oneminch** [comment]
I think I have undone those changes to package-lock.json.

**Review by rashil2000 — APPROVED** [review]

**Review by gpailler — APPROVED** [review]

**Comment by gpailler** [comment]
LGTM, Thanks!

**Comment by rashil2000** [comment]
Just a small question: how do you make use of this in Chromium-based browsers?

**Comment by rashil2000** [comment]
> If the site had the OpenSearch description, it was added to the search engines list automatically. 

I think this still happens. Whenever I visit such a website, Edge adds a search engine in its list automatically. But it didn't do that for the site in this PR, which is why I had to ask.

**Comment by oneminch** [comment]
I tried to add other websites with OpenSearch plugin (like [Sourcegraph](https://sourcegraph.com/search) and [NPM](https://npmjs.com/)) as a search engine, and none of them were added to the Chromium-based browsers. It's definitely weird, or I'm just missing something. There isn't extensive documentation on the matter, either.

**Comment by rashil2000** [comment]
What I have observed is that there seems to be a limit on the number of search engines that Edge can save. I remember having to delete some of them to add a custom engine some time ago.

**Comment by oneminch** [comment]
I only have just one search engine in the list of these browsers since none is my default browser. It's still the same.

**Comment by gpailler** [comment]
We deployed a fix for the open search functionally #37 and now, the search engine is properly added (tested on Edge on my side)
Could you try again?

**Comment by oneminch** [comment]
It's now working on both Edge and Firefox.

**Pull request merged**
